init to moonglow 2.0.9.5

diff --git a/buildroot/bin/build_all_examples b/buildroot/bin/build_all_examples
--- a/buildroot/bin/build_all_examples
+++ b/buildroot/bin/build_all_examples
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Usage:
+# build_all_examples base_branch [resume_point]
 #
 #  build_all_examples [-b|--branch=<branch>] - Branch to fetch from Configurations repo
 #                     [-c|--continue]        - Continue the paused build
@@ -19,20 +19,12 @@
 GITREPO=https://github.com/MarlinFirmware/Configurations.git
 STAT_FILE=./.pio/.buildall
 
-usage() { echo "
-Usage: $SELF [-b|--branch=<branch>] [-d|--debug] [-i|--ini] [-r|--resume=<path>]
-       $SELF [-b|--branch=<branch>] [-d|--debug] [-i|--ini] [-c|--continue]
-       $SELF [-b|--branch=<branch>] [-d|--debug] [-i|--ini] [-s|--skip]
-       $SELF [-b|--branch=<branch>] [-d|--debug] [-n|--nobuild]
-       $SELF [...] branch [resume-point]
-"
-}
+# Check dependencies
+which curl 1>/dev/null 2>&1 || { echo "curl not found! Please install it."; exit ; }
+which git 1>/dev/null 2>&1 || { echo "git not found! Please install it."; exit ; }
 
-# Assume the most recent configs
-BRANCH=import-2.0.x
-unset FIRST_CONF
-EXIT_USAGE=
-LIMIT=1000
+SED=$(command -v gsed 2>/dev/null || command -v sed 2>/dev/null)
+[[ -z "$SED" ]] && { echo "No sed found, please install sed" ; exit 1 ; }
 
 while getopts 'b:cdhil:nqr:sv-:' OFLAG; do
   case "${OFLAG}" in
@@ -63,35 +55,42 @@ while getopts 'b:cdhil:nqr:sv-:' OFLAG; do
   esac
 done
 
-# Extra arguments count as BRANCH, FIRST_CONF
-shift $((OPTIND - 1))
-[[ $# > 0 ]] && { BRANCH=$1 ; shift 1 ; bugout "BRANCH=$BRANCH" ; }
-[[ $# > 0 ]] && { FIRST_CONF=$1 ; shift 1 ; bugout "FIRST_CONF=$FIRST_CONF" ; }
-[[ $# > 0 ]] && { EXIT_USAGE=2 ; echo "too many arguments" ; }
+# Check if called in the right location
+[[ -e "Marlin/src" ]] || { echo -e "This script must be called from a Marlin working copy with:\n ./buildroot/bin/$SELF $1" ; exit ; }
 
-((EXIT_USAGE)) && { usage ; let EXIT_USAGE-- ; exit $EXIT_USAGE ; }
+if [[ $# -lt 1 || $# -gt 2 ]]; then
+  echo "Usage: $SELF base_branch [resume_point]
+  base_branch  - Configuration branch to download and build
+  resume_point - Configuration path to start from"
+  exit
+fi
 
-echo "This script downloads each Configuration and attempts to build it."
+echo "This script downloads all Configurations and builds Marlin with each one."
 echo "On failure the last-built configs will be left in your working copy."
 echo "Restore your configs with 'git checkout -f' or 'git reset --hard HEAD'."
 
+unset BRANCH
+unset FIRST_CONF
 if [[ -f "$STAT_FILE" ]]; then
   IFS='*' read BRANCH FIRST_CONF <"$STAT_FILE"
 fi
 
 # If -c is given start from the last attempted build
-if ((CONTINUE)); then
+if [[ $1 == '-c' ]]; then
   if [[ -z $BRANCH || -z $FIRST_CONF ]]; then
     echo "Nothing to continue"
     exit
   fi
-elif ((CONTSKIP)); then
+elif [[ $1 == '-s' ]]; then
   if [[ -n $BRANCH && -n $FIRST_CONF ]]; then
     SKIP_CONF=1
   else
     echo "Nothing to skip"
     exit
   fi
+else
+  BRANCH=${1:-"import-2.0.x"}
+  FIRST_CONF=$2
 fi
 
 # Check if the current repository has unmerged changes
@@ -109,30 +108,27 @@ TMP=./.pio/build-$BRANCH
 
 # Download Configurations into the temporary folder
 if [[ ! -e "$TMP/README.md" ]]; then
-  echo "Fetching Configurations from GitHub to $TMP"
+  echo "Downloading Configurations from GitHub into $TMP"
   git clone --depth=1 --single-branch --branch "$BRANCH" $GITREPO "$TMP" || { echo "Failed to clone the configuration repository"; exit ; }
 else
-  echo "Using cached Configurations at $TMP"
+  echo "Using previously downloaded Configurations at $TMP"
 fi
 
-echo -e "Start build...\n====================="
+echo -e "Start building now...\n====================="
 shopt -s nullglob
 IFS='
 '
 CONF_TREE=$( ls -d "$TMP"/config/examples/*/ "$TMP"/config/examples/*/*/ "$TMP"/config/examples/*/*/*/ "$TMP"/config/examples/*/*/*/*/ | grep -vE ".+\.(\w+)$" )
+DOSKIP=0
 for CONF in $CONF_TREE ; do
-
   # Get a config's directory name
   DIR=$( echo $CONF | sed "s|$TMP/config/examples/||" )
-
   # If looking for a config, skip others
   [[ $FIRST_CONF ]] && [[ $FIRST_CONF != $DIR && "$FIRST_CONF/" != $DIR ]] && continue
   # Once found, stop looking
   unset FIRST_CONF
-
   # If skipping, don't build the found one
   [[ $SKIP_CONF ]] && { unset SKIP_CONF ; continue ; }
-
   # ...if skipping, don't build this one
   compgen -G "${CONF}Con*.h" > /dev/null || continue
 
